{"cvrfdoc":{"document_title":"Red Hat Security Advisory: python security update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2003:048","type":"Self","url":"https://access.redhat.com/errata/RHSA-2003:048"},{"description":"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=156556","type":"External","url":"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=156556"}]},"aggregate_severity":"Low","document_tracking":{"initial_release_date":"2003-02-12T14:39:00Z","identification":{"id":"RHSA-2003:048"},"revision_history":{"revision":{"date":"2003-02-07T00:00:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-08-23T04:26:00Z","engine":"Red Hat SDEngine 3.0.0"},"current_release_date":"2003-02-07T00:00:00Z","version":"1","status":"Final"},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"security flaw"},"cve":"CVE-2002-1119","references":{"reference":[{"description":"CVE-2002-1119","url":"https://access.redhat.com/security/cve/CVE-2002-1119"},{"description":"bz#1616838: CVE-2002-1119 security flaw","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1616838"}]},"release_date":"2002-08-01T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\nPlease note that this update is available via Red Hat Network.  To use Red\nHat Network, launch the Red Hat Update Agent with the following command:\nup2date\nThis will start an interactive process that will result in the appropriate\nRPMs being upgraded on your system.","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2003:048"}},"ordinal":"1"}],"document_notes":{"note":["An insecure use of a temporary file has been found in Python.","Python is an interpreted, interactive, object-oriented programming\nlanguage.\nZack Weinberg discovered that os._execvpe from os.py in Python 2.2.1 and\nearlier creates temporary files with predictable names. This could allow\nlocal users to execute arbitrary code via a symlink attack\nAll users should upgrade to these errata packages which include a patch to\npython 1.5.2 to correct this issue.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}