{"cvrfdoc":{"document_title":"Red Hat Security Advisory: python security update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2009:1176","type":"Self","url":"https://access.redhat.com/errata/RHSA-2009:1176"},{"description":"http://www.redhat.com/security/updates/classification/#moderate","type":"External","url":"http://www.redhat.com/security/updates/classification/#moderate"}]},"aggregate_severity":"Moderate","document_tracking":{"initial_release_date":"2009-07-27T09:22:00Z","identification":{"id":"RHSA-2009:1176"},"revision_history":{"revision":{"date":"2009-07-27T05:22:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-08-23T04:30:00Z","engine":"Red Hat SDEngine 3.0.0"},"current_release_date":"2009-07-27T05:22:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"5Client","product_reference":"python-0:2.4.3-24.el5_3.6","full_product_name":{"product_id":"5Client:python-0:2.4.3-24.el5_3.6","cpe":"cpe:/o:redhat:enterprise_linux:5::client","product_name":"python-0:2.4.3-24.el5_3.6 as a component of Red Hat Enterprise Linux Desktop (v. 5 client)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"5Client-Workstation","product_reference":"python-0:2.4.3-24.el5_3.6","full_product_name":{"product_id":"5Client-Workstation:python-0:2.4.3-24.el5_3.6","cpe":"cpe:/o:redhat:enterprise_linux:5::client_workstation","product_name":"python-0:2.4.3-24.el5_3.6 as a component of Red Hat Enterprise Linux Desktop Workstation (v. 5 client)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"5Server","product_reference":"python-0:2.4.3-24.el5_3.6","full_product_name":{"product_id":"5Server:python-0:2.4.3-24.el5_3.6","cpe":"cpe:/o:redhat:enterprise_linux:5::server","product_name":"python-0:2.4.3-24.el5_3.6 as a component of Red Hat Enterprise Linux (v. 5 server)"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat Enterprise Linux","type":"Product Family","branch":[{"name":"Red Hat Enterprise Linux Desktop (v. 5 client)","full_product_name":{"product_id":"5Client","cpe":"cpe:/o:redhat:enterprise_linux:5::client","product_name":"Red Hat Enterprise Linux Desktop (v. 5 client)"},"type":"Product Name"},{"name":"Red Hat Enterprise Linux Desktop Workstation (v. 5 client)","full_product_name":{"product_id":"5Client-Workstation","cpe":"cpe:/o:redhat:enterprise_linux:5::client_workstation","product_name":"Red Hat Enterprise Linux Desktop Workstation (v. 5 client)"},"type":"Product Name"},{"name":"Red Hat Enterprise Linux (v. 5 server)","full_product_name":{"product_id":"5Server","cpe":"cpe:/o:redhat:enterprise_linux:5::server","product_name":"Red Hat Enterprise Linux (v. 5 server)"},"type":"Product Name"}]},{"name":"python-0:2.4.3-24.el5_3.6","full_product_name":{"product_id":"python-0:2.4.3-24.el5_3.6","cpe":"cpe:/o:redhat:enterprise_linux:5::client","product_name":"python-2.4.3-24.el5_3.6.src.rpm"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"python off-by-one locale.strxfrm() (possible memory disclosure)"},"cve":"CVE-2007-2052","references":{"reference":[{"description":"CVE-2007-2052","url":"https://access.redhat.com/security/cve/CVE-2007-2052"},{"description":"bz#235093: CVE-2007-2052 python off-by-one locale.strxfrm() (possible memory disclosure)","url":"https://bugzilla.redhat.com/show_bug.cgi?id=235093"}]},"release_date":"2007-04-02T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2007-04-02T00:00:00Z","ordinal":"1"},{"notes":{"note":"python imageop module heap corruption"},"cve":"CVE-2007-4965","references":{"reference":[{"description":"CVE-2007-4965","url":"https://access.redhat.com/security/cve/CVE-2007-4965"},{"description":"bz#295971: CVE-2007-4965 python imageop module heap corruption","url":"https://bugzilla.redhat.com/show_bug.cgi?id=295971"}]},"release_date":"2007-09-16T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2007-09-18T00:00:00Z","ordinal":"2"},{"notes":{"note":"python: integer signedness error in the zlib extension module"},"cve":"CVE-2008-1721","references":{"reference":[{"description":"CVE-2008-1721","url":"https://access.redhat.com/security/cve/CVE-2008-1721"},{"description":"bz#442005: CVE-2008-1721 python: integer signedness error in the zlib extension module","url":"https://bugzilla.redhat.com/show_bug.cgi?id=442005"}]},"release_date":"2008-04-09T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-04-09T00:00:00Z","ordinal":"3"},{"notes":{"note":"python: PyString_FromStringAndSize does not check for negative size values"},"cve":"CVE-2008-1887","references":{"reference":[{"description":"CVE-2008-1887","url":"https://access.redhat.com/security/cve/CVE-2008-1887"},{"description":"bz#443810: CVE-2008-1887 python: PyString_FromStringAndSize does not check for negative size values","url":"https://bugzilla.redhat.com/show_bug.cgi?id=443810"}]},"release_date":"2008-04-08T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2008-04-18T00:00:00Z","ordinal":"4"},{"notes":{"note":"python: Multiple integer overflows in python core"},"cve":"CVE-2008-2315","references":{"reference":[{"description":"CVE-2008-2315","url":"https://access.redhat.com/security/cve/CVE-2008-2315"},{"description":"bz#455008: CVE-2008-2315 python: Multiple integer overflows in python core","url":"https://bugzilla.redhat.com/show_bug.cgi?id=455008"}]},"release_date":"2008-07-31T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-07-02T00:00:00Z","ordinal":"5"},{"notes":{"note":"python: Multiple buffer overflows in unicode processing"},"cve":"CVE-2008-3142","references":{"reference":[{"description":"CVE-2008-3142","url":"https://access.redhat.com/security/cve/CVE-2008-3142"},{"description":"bz#454990: CVE-2008-3142 python: Multiple buffer overflows in unicode processing","url":"https://bugzilla.redhat.com/show_bug.cgi?id=454990"}]},"release_date":"2008-04-11T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-07-02T00:00:00Z","ordinal":"6"},{"notes":{"note":"python: Multiple integer overflows discovered by Google"},"cve":"CVE-2008-3143","references":{"reference":[{"description":"CVE-2008-3143","url":"https://access.redhat.com/security/cve/CVE-2008-3143"},{"description":"bz#455013: CVE-2008-3143 python: Multiple integer overflows discovered by Google","url":"https://bugzilla.redhat.com/show_bug.cgi?id=455013"}]},"release_date":"2008-02-14T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-07-03T00:00:00Z","ordinal":"7"},{"notes":{"note":"python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function"},"cve":"CVE-2008-3144","references":{"reference":[{"description":"CVE-2008-3144","url":"https://access.redhat.com/security/cve/CVE-2008-3144"},{"description":"bz#455018: CVE-2008-3144 python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function","url":"https://bugzilla.redhat.com/show_bug.cgi?id=455018"}]},"release_date":"2008-06-02T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-07-03T00:00:00Z","ordinal":"8"},{"notes":{"note":"python: imageop module multiple integer overflows"},"cve":"CVE-2008-4864","references":{"reference":[{"description":"CVE-2008-4864","url":"https://access.redhat.com/security/cve/CVE-2008-4864"},{"description":"bz#469656: CVE-2008-4864 python: imageop module multiple integer overflows","url":"https://bugzilla.redhat.com/show_bug.cgi?id=469656"}]},"release_date":"2008-10-19T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-10-19T00:00:00Z","ordinal":"9"},{"notes":{"note":"python: stringobject, unicodeobject integer overflows"},"cve":"CVE-2008-5031","references":{"reference":[{"description":"CVE-2008-5031","url":"https://access.redhat.com/security/cve/CVE-2008-5031"},{"description":"bz#470915: CVE-2008-5031 python: stringobject, unicodeobject integer overflows","url":"https://bugzilla.redhat.com/show_bug.cgi?id=470915"}]},"release_date":"2008-10-19T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["5Client-Workstation:python-0:2.4.3-24.el5_3.6","5Client:python-0:2.4.3-24.el5_3.6","5Server:python-0:2.4.3-24.el5_3.6"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\nThis update is available via Red Hat Network. Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2009:1176"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2008-10-19T00:00:00Z","ordinal":"10"}],"document_notes":{"note":["Updated python packages that fix multiple security issues are now available\nfor Red Hat Enterprise Linux 5.\nThis update has been rated as having moderate security impact by the Red\nHat Security Response Team.","Python is an interpreted, interactive, object-oriented programming\nlanguage.\nWhen the assert() system call was disabled, an input sanitization flaw was\nrevealed in the Python string object implementation that led to a buffer\noverflow. The missing check for negative size values meant the Python\nmemory allocator could allocate less memory than expected. This could\nresult in arbitrary code execution with the Python interpreter's\nprivileges. (CVE-2008-1887)\nMultiple buffer and integer overflow flaws were found in the Python Unicode\nstring processing and in the Python Unicode and string object\nimplementations. An attacker could use these flaws to cause a denial of\nservice (Python application crash). (CVE-2008-3142, CVE-2008-5031)\nMultiple integer overflow flaws were found in the Python imageop module. If\na Python application used the imageop module to process untrusted images,\nit could cause the application to disclose sensitive information, crash or,\npotentially, execute arbitrary code with the Python interpreter's\nprivileges. (CVE-2007-4965, CVE-2008-4864)\nMultiple integer underflow and overflow flaws were found in the Python\nsnprintf() wrapper implementation. An attacker could use these flaws to\ncause a denial of service (memory corruption). (CVE-2008-3144)\nMultiple integer overflow flaws were found in various Python modules. An\nattacker could use these flaws to cause a denial of service (Python\napplication crash). (CVE-2008-2315, CVE-2008-3143)\nAn integer signedness error, leading to a buffer overflow, was found\nin the Python zlib extension module. If a Python application requested\nthe negative byte count be flushed for a decompression stream, it could\ncause the application to crash or, potentially, execute arbitrary code\nwith the Python interpreter's privileges. (CVE-2008-1721)\nA flaw was discovered in the strxfrm() function of the Python locale\nmodule. Strings generated by this function were not properly\nNULL-terminated, which could possibly cause disclosure of data stored in\nthe memory of a Python application using this function. (CVE-2007-2052)\nRed Hat would like to thank David Remahl of the Apple Product Security team\nfor responsibly reporting the CVE-2008-2315 issue.\nAll Python users should upgrade to these updated packages, which contain\nbackported patches to correct these issues.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}